### ISSUE TITLE
Typo in point 9 of the security manual

### ISSUE THREAD

**Issue by RRoodselaar** [MyEtherWallet/knowledge-base-v3#66]
URL: https://myetherwallet.github.io/knowledge-base/getting-started/protecting-yourself-and-your-funds.html

"9. Always verify that the site you landed on is legit.

    Especially if you are about to entire your private key or download an application. ..."

The word "entire" in the first sentence should be "enter".

**Comment by crines** [comment]
This issue should be closed. Change revision of typo from 'entire' to 'enter' is complete. Committed to master 5 days ago with/as #68; not uploaded to website yet. crines 2/24/2018 PST
REF: commit [c1b5da8](https://github.com/MyEtherWallet/knowledge-base/commit/c1b5da8c7910fe2c0c1798c3204af91ca3979f75)

**Comment by kvhnuke** [comment]
Thank you!
