### ISSUE TITLE
This doesn't really help

### ISSUE THREAD

**Issue by taygatayga** [MyEtherWallet/knowledge-base-v3#76]
The article doesn't explain what is blocking popups (MEW? Trezor? Adblock?) or where the setting can be found in order to change it.

**Comment by keonglee** [comment]
帮我

**Comment by keonglee** [comment]
谢谢，，我没读到书，，，所以什么都不会

**Comment by gamalielhere** [comment]
@taygatayga which article are you referring to?

**Comment by taygatayga** [comment]
I'm not sure why this comment has flagged up as an issue now. 

I commented on an article in June and the comment no longer seems to be associated with the article. 

The fact that two people have replied to my comment in the past 24 hours while no-one replied in 3 months suggests to me there's a glitch somewhere. 

Please disregard my comment as the issue is resolved and I cannot recall the article on which I was commenting.

**Comment by gamalielhere** [comment]
@taygatayga Thanks for letting me know. If you do come across the article again, don't hesitate to open another issue or comment on this one.
